/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_PROTO_MESSAGES_PB_H_INCLUDED
#define PB_PROTO_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _response_Result {
    response_Result_OK = 0, /* sed, ping or crecevie ok */
    response_Result_NO_MSG = 1, /* no message on queue */
    response_Result_NOK = 5, /* error */
    response_Result_NOMQTT = 7 /* no mqtt error */
} response_Result;

/* Struct definitions */
typedef struct _request_Ping {
    int32_t num;
} request_Ping;

typedef struct _request_Send {
    char queue[12];
    char payload[128];
    bool persist;
} request_Send;

typedef struct _request_Subscribe {
    char queue[12];
    bool clear;
} request_Subscribe;

typedef struct _request_Operation {
    pb_size_t which_op;
    union {
        request_Ping ping;
        request_Send send;
        request_Subscribe qRequest;
    } op;
} request_Operation;

typedef struct _request {
    char client_id[10];
    pb_size_t operations_count;
    request_Operation operations[5];
    int32_t message_type;
    pb_byte_t client_mac[6];
} request;

typedef struct _response_OpResponse {
    response_Result result_code;
    char payload[128];
} response_OpResponse;

typedef struct _response {
    pb_size_t opResponses_count;
    response_OpResponse opResponses[5];
    int32_t message_type;
    pb_byte_t client_mac[6];
} response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _response_Result_MIN response_Result_OK
#define _response_Result_MAX response_Result_NOMQTT
#define _response_Result_ARRAYSIZE ((response_Result)(response_Result_NOMQTT+1))







#define response_OpResponse_result_code_ENUMTYPE response_Result


/* Initializer values for message structs */
#define request_init_default                     {"", 0, {request_Operation_init_default, request_Operation_init_default, request_Operation_init_default, request_Operation_init_default, request_Operation_init_default}, 0, {0}}
#define request_Ping_init_default                {0}
#define request_Send_init_default                {"", "", 0}
#define request_Subscribe_init_default           {"", 0}
#define request_Operation_init_default           {0, {request_Ping_init_default}}
#define response_init_default                    {0, {response_OpResponse_init_default, response_OpResponse_init_default, response_OpResponse_init_default, response_OpResponse_init_default, response_OpResponse_init_default}, 0, {0}}
#define response_OpResponse_init_default         {_response_Result_MIN, ""}
#define request_init_zero                        {"", 0, {request_Operation_init_zero, request_Operation_init_zero, request_Operation_init_zero, request_Operation_init_zero, request_Operation_init_zero}, 0, {0}}
#define request_Ping_init_zero                   {0}
#define request_Send_init_zero                   {"", "", 0}
#define request_Subscribe_init_zero              {"", 0}
#define request_Operation_init_zero              {0, {request_Ping_init_zero}}
#define response_init_zero                       {0, {response_OpResponse_init_zero, response_OpResponse_init_zero, response_OpResponse_init_zero, response_OpResponse_init_zero, response_OpResponse_init_zero}, 0, {0}}
#define response_OpResponse_init_zero            {_response_Result_MIN, ""}

/* Field tags (for use in manual encoding/decoding) */
#define request_Ping_num_tag                     1
#define request_Send_queue_tag                   1
#define request_Send_payload_tag                 2
#define request_Send_persist_tag                 3
#define request_Subscribe_queue_tag              1
#define request_Subscribe_clear_tag              2
#define request_Operation_ping_tag               4
#define request_Operation_send_tag               5
#define request_Operation_qRequest_tag           6
#define request_client_id_tag                    1
#define request_operations_tag                   2
#define request_message_type_tag                 3
#define request_client_mac_tag                   4
#define response_OpResponse_result_code_tag      1
#define response_OpResponse_payload_tag          2
#define response_opResponses_tag                 1
#define response_message_type_tag                2
#define response_client_mac_tag                  3

/* Struct field encoding specification for nanopb */
#define request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   client_id,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  operations,        2) \
X(a, STATIC,   SINGULAR, INT32,    message_type,      3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, client_mac,        4)
#define request_CALLBACK NULL
#define request_DEFAULT NULL
#define request_operations_MSGTYPE request_Operation

#define request_Ping_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    num,               1)
#define request_Ping_CALLBACK NULL
#define request_Ping_DEFAULT NULL

#define request_Send_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   queue,             1) \
X(a, STATIC,   SINGULAR, STRING,   payload,           2) \
X(a, STATIC,   SINGULAR, BOOL,     persist,           3)
#define request_Send_CALLBACK NULL
#define request_Send_DEFAULT NULL

#define request_Subscribe_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   queue,             1) \
X(a, STATIC,   SINGULAR, BOOL,     clear,             2)
#define request_Subscribe_CALLBACK NULL
#define request_Subscribe_DEFAULT NULL

#define request_Operation_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,ping,op.ping),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,send,op.send),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,qRequest,op.qRequest),   6)
#define request_Operation_CALLBACK NULL
#define request_Operation_DEFAULT NULL
#define request_Operation_op_ping_MSGTYPE request_Ping
#define request_Operation_op_send_MSGTYPE request_Send
#define request_Operation_op_qRequest_MSGTYPE request_Subscribe

#define response_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  opResponses,       1) \
X(a, STATIC,   SINGULAR, INT32,    message_type,      2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, client_mac,        3)
#define response_CALLBACK NULL
#define response_DEFAULT NULL
#define response_opResponses_MSGTYPE response_OpResponse

#define response_OpResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    result_code,       1) \
X(a, STATIC,   SINGULAR, STRING,   payload,           2)
#define response_OpResponse_CALLBACK NULL
#define response_OpResponse_DEFAULT NULL

extern const pb_msgdesc_t request_msg;
extern const pb_msgdesc_t request_Ping_msg;
extern const pb_msgdesc_t request_Send_msg;
extern const pb_msgdesc_t request_Subscribe_msg;
extern const pb_msgdesc_t request_Operation_msg;
extern const pb_msgdesc_t response_msg;
extern const pb_msgdesc_t response_OpResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define request_fields &request_msg
#define request_Ping_fields &request_Ping_msg
#define request_Send_fields &request_Send_msg
#define request_Subscribe_fields &request_Subscribe_msg
#define request_Operation_fields &request_Operation_msg
#define response_fields &response_msg
#define response_OpResponse_fields &response_OpResponse_msg

/* Maximum encoded size of messages (where known) */
#define request_Operation_size                   148
#define request_Ping_size                        11
#define request_Send_size                        145
#define request_Subscribe_size                   15
#define request_size                             785
#define response_OpResponse_size                 132
#define response_size                            694

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
